=== BlocksInMotion/BlocksInMotion/data/dtd/config.dtd
<!ELEMENT config (#PCDATA | screen | gui | projection | input | sleep | graphic | graphic_device | inferred | opencl | bim)*>
<!ELEMENT screen (#PCDATA)*>
<!ATTLIST screen
	width CDATA #REQUIRED
	height CDATA #REQUIRED
	fullscreen CDATA #REQUIRED
	vsync CDATA #REQUIRED
	stereo CDATA #REQUIRED
>
<!ELEMENT gui (#PCDATA)*>
<!ATTLIST gui
	dpi CDATA #REQUIRED
	anti_aliasing CDATA #REQUIRED
>
<!ELEMENT projection (#PCDATA)*>
<!ATTLIST projection
	fov CDATA #REQUIRED
	near CDATA #REQUIRED
	far CDATA #REQUIRED
>
<!ELEMENT input (#PCDATA)*>
<!ATTLIST input
	key_repeat CDATA #REQUIRED
	ldouble_click CDATA #REQUIRED
	mdouble_click CDATA #REQUIRED
	rdouble_click CDATA #REQUIRED
>
<!ELEMENT sleep (#PCDATA)*>
<!ATTLIST sleep
	time CDATA #REQUIRED
>
<!ELEMENT graphic (#PCDATA)*>
<!ATTLIST graphic
	filtering CDATA #REQUIRED
	anisotropic CDATA #REQUIRED
	anti_aliasing CDATA #REQUIRED
>
<!ELEMENT graphic_device (#PCDATA)*>
<!ATTLIST graphic_device
	disabled_extensions CDATA #REQUIRED
	force_device CDATA #REQUIRED
	force_vendor CDATA #REQUIRED
>
<!ELEMENT inferred (#PCDATA)*>
<!ATTLIST inferred
	upscaling CDATA #REQUIRED
	geometry_light_scaling CDATA #REQUIRED
>
<!ELEMENT opencl (#PCDATA)*>
<!ATTLIST opencl
	platform CDATA #REQUIRED
	clear_cache CDATA #REQUIRED
	restrict CDATA #REQUIRED
>
<!ELEMENT debug (#PCDATA)*>
<!ATTLIST debug
	free_cam CDATA #REQUIRED
	player_gfx CDATA #REQUIRED
>
<!ELEMENT bim (#PCDATA | gfx | forcefield | volume | menu | controls)*>
<!ELEMENT gfx (#PCDATA | texture | particles)*>
<!ELEMENT texture (#PCDATA)*>
<!ATTLIST texture
	quality CDATA #REQUIRED
>
<!ELEMENT particles (#PCDATA)*>
<!ATTLIST particles
        enabled CDATA #REQUIRED
>
<!ELEMENT volume (#PCDATA)*>
<!ATTLIST volume
	music CDATA #REQUIRED
	sound CDATA #REQUIRED
>
<!ELEMENT forcefield (#PCDATA)*>
<!ATTLIST forcefield
	grab_color CDATA #REQUIRED
	push_color CDATA #REQUIRED
	swap_color CDATA #REQUIRED
  background_selecting CDATA #REQUIRED
  background_selected CDATA #REQUIRED
  tex_interpolation CDATA #REQUIRED
  line_interval CDATA #REQUIRED
  time_denominator CDATA #REQUIRED
>
<!ELEMENT menu (#PCDATA)*>
<!ATTLIST menu
	disabled CDATA #REQUIRED
>
<!ELEMENT controls (#PCDATA)*>
<!ATTLIST controls
	pg_pull CDATA #REQUIRED
	pg_push CDATA #REQUIRED
	pg_gravity CDATA #REQUIRED
	forwards CDATA #REQUIRED
	backwards CDATA #REQUIRED
	left CDATA #REQUIRED
	right CDATA #REQUIRED
	jump CDATA #REQUIRED
	console CDATA #REQUIRED
>

=== BlocksInMotion/BlocksInMotion/data/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE config PUBLIC "-//A2E//DTD config 1.0//EN" "config.dtd">
<config>
	<!-- screen resolution and fullscreen/vsync settings (stereo serves no purpose right now) -->
	<screen width="1280" height="720" fullscreen="0" vsync="0" stereo="0"/>

	<!--
	 dpi: use this to overwrite the auto-detected dpi value (0: use auto-detect)
	 anti_aliasing options: 0 - max MSAA value allowed by graphics card (8 is recommended)
	-->
	<gui dpi="0" anti_aliasing="8"/>

	<!-- you might want to change the field of view, but near/far should remain at 1/1000 -->
	<projection fov="72.0" near="0.1" far="1000.0"/>

	<!-- there should be no need to change these -->
	<input key_repeat="0" ldouble_click="10" mdouble_click="10" rdouble_click="10"/>

	<!-- this will sleep the program for the specified amount of milliseconds after each rendered frame -->
	<sleep time="0"/>

	<!--
	 filtering options: POINT, LINEAR, BILINEAR, TRILINEAR
	 anisotropic options: 0 (disabled), 1 - 16
	 anti_aliasing options: NONE, FXAA, 2xSSAA, 4/3xSSAA+FXAA, 2xSSAA+FXAA (others are currently unsupported)
	-->
	<graphic filtering="TRILINEAR" anisotropic="16" anti_aliasing="FXAA"/>

	<!--
	 upscaling: sets the upscaling factor
		e.g. a value of 2.0 with screen width/height set to 1280*720 will lead to rendering at 640*360 and then scaling it back up to 1280*720
	 geometry_light_scaling: sets the additional scaling of the geometry and light buffer (note: it is not recommended to change this value!)
		valid values are: 0.5, 0.625, 0.75, 0.875, 1.0 (anything above 1.0 has no effect, anything below 0.5 will lead to broken rendering)
	-->
	<inferred upscaling="1.0" geometry_light_scaling="1.0"/>

	<!-- unless you know what you're doing, don't change the following settings
	 opencl platform options: either the opencl platform index (starting by 0) or "cuda" on supported platforms (OS X and Linux only)
	 opencl restrict options: if this is set to any of (or a list of) "CPU", "GPU" or "ACCELERATOR", only those kind/type of devices are used
	-->
	<graphic_device disabled_extensions="" force_device="" force_vendor=""/>
	<opencl platform="0" clear_cache="1" restrict="CPU"/>
	
	<!-- application specific settings -->
	<bim>
		<gfx>
			<!-- quality: ultra (1024px), high (512px), mid (256px) or low (128px) -->
			<texture quality="ultra"/>
			<particles enabled="true"/>
		</gfx>
		<!-- force field visualization -->
		<forcefield grab_color="0.0,0.0,1.0,1.0" push_color="1.0,0.0,0.0,1.0" swap_color="0.0,1.0,0.0,1.0" background_selecting="0.0,0.0,0.0,0.0"
					background_selected="0.0,0.0,0.0,1.0" tex_interpolation="0.28" line_interval="0.11,0.15"
					time_denominator="2000.0"/>
		<!-- music/sound: 0.0 - 1.0 -->
		<volume music="0.3" sound="1.0"/>
		<!-- menu: can be disabled for debugging purposes and direct level loading -->
		<menu disabled="false"/>
		<!-- controls: change these ingame -->
		<controls pg_pull="8589934592,0" pg_push="4294967296,0" pg_gravity="12884901888,0" left="97,1073741904" forwards="119,1073741906" right="100,1073741903" backwards="115,1073741905" jump="32,0" console="9,0"/>
	</bim>
</config>
